In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.2.1 -> 22.2.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np
a = np.array([1, 2, 3])


In [3]:
a

array([1, 2, 3])

In [4]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [5]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [6]:
np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [7]:
print(np.arange(4))
print(np.arange(0, 10, 2))

[0 1 2 3]
[0 2 4 6 8]


In [8]:
np.arange(2,29,5)

array([ 2,  7, 12, 17, 22, 27])

In [9]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8,])

In [10]:
np.append(arr,[1,2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [11]:
np.delete(arr, 1)

array([1, 3, 4, 5, 6, 7, 8])

In [12]:
arr = np.array([2,1,5,3,7,4,6,8])

In [13]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
array_example = np.array([[[ 0,1,2,3],
[4,5,6,7]],
[[0,1,2,3],
[4,5,6,7]],
[[0,1,2,3],

[4,5,6,7]]])

In [15]:
print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [16]:
array_example.ndim

3

In [17]:
array_example.size

24

In [18]:
array_example.shape

(3, 2, 4)

In [19]:
arr_one = np.array([[1,2,3,4,5]])
arr_one.ndim

2

In [20]:
arr_one.size

5

In [21]:
arr_one.shape

(1, 5)

In [22]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [23]:
b = a.reshape(3,2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [24]:
a.reshape(6,1)


array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [25]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [26]:
a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [27]:
row_vector = a[np.newaxis,:]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [28]:
col_vector = a[:,np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [29]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [30]:
b = np.expand_dims(a,axis=1)
b.shape

(6, 1)

In [31]:
c = np.expand_dims(a,axis=0)
c.shape

(1, 6)

In [32]:
data = np.array([1,2,3])
print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

[1 2 3]
1
2
[1 2]
[2 3]
[2 3]


In [33]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [34]:
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]


In [35]:
five_up = (a>=5)

print(a[five_up])
print(a[a>=5])


[ 5  6  7  8  9 10 11 12]
[ 5  6  7  8  9 10 11 12]


In [36]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [37]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [38]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

In [39]:
a_1 = np.array([[1 ,1],
[2,2]])

In [40]:
a_2 = np.array([[3 ,3],
[4,4]])

In [41]:
np.vstack((a_1,a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [42]:
np.hstack((a_1,a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [43]:
import numpy as np

In [44]:
c = np.array ([[1,2,3,4,5,6,7,8,9,10,11,12],
[13,14,15,16,17,18,19,20,21,22,23,24]])
c


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [45]:
np.hsplit(c,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [46]:
np.split(c,2,axis=1)

[array([[ 1,  2,  3,  4,  5,  6],
        [13, 14, 15, 16, 17, 18]]),
 array([[ 7,  8,  9, 10, 11, 12],
        [19, 20, 21, 22, 23, 24]])]

In [47]:
splitted_c= np.split(c,2,axis=1)

In [48]:
splitted_c

[array([[ 1,  2,  3,  4,  5,  6],
        [13, 14, 15, 16, 17, 18]]),
 array([[ 7,  8,  9, 10, 11, 12],
        [19, 20, 21, 22, 23, 24]])]

In [49]:
splitted_c[0]

array([[ 1,  2,  3,  4,  5,  6],
       [13, 14, 15, 16, 17, 18]])

In [50]:
splitted_c[1]

array([[ 7,  8,  9, 10, 11, 12],
       [19, 20, 21, 22, 23, 24]])

In [51]:
splitted_c= np.split(c,2)
splitted_c

[array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]]),
 array([[13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])]

In [52]:
splitted_c[0]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [53]:
splitted_c[1]

array([[13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [54]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [55]:
b= a.view()

In [56]:
h = a.copy()
h

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [57]:
a = np.array([1,2,3,4])
a.sum()

10

In [58]:
b = np.array([[1,1],[2,2]])
b

array([[1, 1],
       [2, 2]])

In [59]:
b.sum(axis=0)

array([3, 3])

In [60]:
b.sum (axis=1)

array([2, 4])

In [61]:
data = np.array([1,2])
data

array([1, 2])

In [62]:
ones = np.ones(2)
ones


array([1., 1.])

In [63]:
data+ones

array([2., 3.])

In [64]:
data*data

array([1, 4])

In [65]:
data/data

array([1., 1.])

In [66]:
data*2

array([2, 4])

In [67]:
A = np.array([[0.45053314,0.17296777,0.34376245,0.5510652],
[0.54627315,0.05093587,0.40067661,0.55645993],
[0.12697628,0.82485143,0.26590556,0.56917101]])
print(A)

[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.12697628 0.82485143 0.26590556 0.56917101]]


In [68]:
A.sum()

4.8595784

In [69]:
A.min()

0.05093587

In [70]:
A.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [71]:
A.max()

0.82485143

In [72]:
A.max(axis=1)

array([0.5510652 , 0.55645993, 0.82485143])

In [73]:
A.std()

0.21392120766089617

In [74]:
print(np.ones((3,2)))
print(np.zeros((3,2)))
print(np.random.random((3,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.71093198 0.05161367]
 [0.2132823  0.75827658]
 [0.23110611 0.04166031]]


In [75]:
data = np.array([[1,2],[3,4]])
print(data)

[[1 2]
 [3 4]]


In [76]:
ones = np.ones([2,2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [77]:
print(data+ones)

[[2. 3.]
 [4. 5.]]


In [78]:
ones_row = np.ones([1,2])
print(ones_row)

[[1. 1.]]


In [79]:
print(data+ones_row)

[[2. 3.]
 [4. 5.]]


In [80]:
a_1= np.array ([[1,2,3],[4,5,6]])
print(a_1)
print(a_1.shape)


a_2= np.array ([[7,8],[9,10],[11,12]])
print(a_2)
print(a_2.shape)




[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [81]:
np.dot(a_1,a_2)

array([[ 58,  64],
       [139, 154]])

In [82]:
data = np.array([[1,2],[3,4],[5,6]])

print(data)
print(data[0])
print(data[1])
print(data[2])
print(data[0,1])
print(data[1:3])
print(data[0:2,1])


[[1 2]
 [3 4]
 [5 6]]
[1 2]
[3 4]
[5 6]
2
[[3 4]
 [5 6]]
[2 4]


In [83]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [84]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [85]:
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 4 6]


In [86]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [87]:
print(data.T)

[[1 3 5]
 [2 4 6]]


In [88]:
data_col=np.array([[1,2,3,4,5,6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [89]:
data_col.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [90]:
data_col.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [91]:
arr = np.arange(6).reshape((2,3))
print(arr)

[[0 1 2]
 [3 4 5]]


In [92]:
ndarr = np.array([[[1,2],[3,4]],
[[5,6],[7,8]]])
print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [93]:
print(np.ones((4,3,2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [94]:
print(np.zeros((4,3,2)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [95]:
print(np.random.random((4,3,2)))

[[[0.40423872 0.02472075]
  [0.94496897 0.05564572]
  [0.81118517 0.33616921]]

 [[0.26188209 0.906164  ]
  [0.07295249 0.31448737]
  [0.438095   0.31664166]]

 [[0.97021219 0.89905123]
  [0.37081898 0.27447195]
  [0.63742923 0.09891203]]

 [[0.77431423 0.13166166]
  [0.25136248 0.36281226]
  [0.49515438 0.97309113]]]


In [96]:
arrflat = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [97]:
arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [98]:
error = (1/n) * np.sum(np.square(observed - prediction))

NameError: name 'n' is not defined

In [ ]:
import numpy as np